// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"github.com/kieron-pivotal/birdpedia/birds/handlers"
	"github.com/kieron-pivotal/birdpedia/birds/storage/db"
	"github.com/kieron-pivotal/birdpedia/database"
	"github.com/kieron-pivotal/birdpedia/routes"
)

// Injectors from wire.go:

func InitialiseRouter() (*mux.Router, error) {
	connectionString := _wireConnectionStringValue
	sqlDB, err := database.NewPostgresConnection(connectionString)
	if err != nil {
		return nil, err
	}
	store := db.NewDBStore(sqlDB)
	handler := handlers.NewHandler(store)
	router := routes.NewRouter(handler)
	return router, nil
}

var (
	_wireConnectionStringValue = database.ConnectionString("host=/var/run/postgresql dbname=bird_encyclopedia sslmode=disable")
)
